MANDA-29: изменил скелет проекта, добавил черновой перехватчик и auth…
mandarine-io/Frontend pull request #3
Opened 2024-10-18 04:11 UTC by nipoks

…context

2024-10-18 17:34 UTC, ptrvsrg requested changes

2024-10-18 17:34 UTC, ptrvsrg commented on src/contexts/AuthContext/AuthContext.tsx
> +const BACKEND_URL = 'https://dev.mandarine-app.ru/api'
Это можно вынести в .env файл? Нехорошо такое иметь в коде

2024-10-18 17:34 UTC, ptrvsrg commented on src/contexts/AuthContext/AuthContext.tsx
> +            refreshToken: output.refreshToken,
Обговорили о том, что у фронта нет доступа к Refresh JWT, он будет храниться в Http Only cookie, и доступа из JS к ним нет

2024-10-18 17:34 UTC, ptrvsrg commented on src/contexts/AuthContext/AuthContext.tsx
> +            id: decode.userId || '',
В JWT добавляю следующие клеймы:
```go
jwt.MapClaims{
	"iss":      jwtIssuer,
	"sub":      userEntity.ID.String(),
	"iat":      time.Now().Unix(),
	"exp":      time.Now().Add(time.Duration(cfg.AccessTokenTTL) * time.Second).Unix(),
	"jti":      jti,
	"username": userEntity.Username,
	"email":    userEntity.Email,
	"role":     userEntity.Role.Name,
},
```

Доставай клеймы по правильным ключам

2024-10-18 17:34 UTC, ptrvsrg commented on src/contexts/AuthContext/AuthContext.tsx
> +            role: decode.role as Role,
```go
const (
	RoleUser  = "user"
	RoleAdmin = "admin"
)
```

2024-10-18 17:34 UTC, ptrvsrg commented on src/contexts/AuthContext/AuthContext.tsx
> +                url: `${BACKEND_URL}/user/authorize`,
Чекни redoc, такого эндпоинта нет. `/v0/auth/login`

2024-10-18 17:34 UTC, ptrvsrg commented on src/contexts/AuthContext/AuthContext.tsx
> +                url: `${BACKEND_URL}/auth/refresh`,
`/v0/auth/refresh`

2024-10-18 17:34 UTC, ptrvsrg commented on src/contexts/AuthContext/AuthContext.tsx
> +            setState(undefined)
в redoc есть эндпоинт `/v0/auth/logout`
его нужно вызвать и удалить токену из стораджа

> _**NOTE:**_ Заметь, что `/v0/auth/logout` защищенный

2024-10-18 17:34 UTC, ptrvsrg commented on src/contexts/AuthContext/AuthContext.types.ts
> +    refreshToken: string
Чек redoc

2024-10-18 17:34 UTC, ptrvsrg commented on src/contexts/AuthContext/AuthContext.types.ts
> +export interface AccessJwtPayload extends JwtPayload {
отписал выше про клеймы

2024-10-18 17:34 UTC, ptrvsrg commented on src/contexts/AuthContext/AuthContext.types.ts
> +    refreshToken: string
отписал выше про рефреш токен

2024-10-18 17:34 UTC, ptrvsrg commented on src/contexts/user/UserContext.ts
> +    MASTER = 'MASTER',
Отписал выше про роли

2024-10-18 17:34 UTC, ptrvsrg commented on src/contexts/user/UserContext.ts
> +    refreshToken: string
отписал выше про рефреш токен

2024-10-18 17:34 UTC, ptrvsrg commented on src/common/interceptors/AuthInterceptor.tsx
> +                    router.push('/', 'root');
наверное нужно вызвать logout, чтобы удалить устареший UserContext

2024-10-20 14:18 UTC, nipoks commented on src/contexts/AuthContext/AuthContext.tsx
> +            refreshToken: output.refreshToken,
пустой запрос кидать на бэк

2024-10-27 10:49 UTC, nipoks commented on src/contexts/AuthContext/AuthContext.tsx
> +            role: decode.role as Role,
Почему такие роли? предполагались же клиенты и мастера (как нам отдавать разные страницы профиля)

2024-11-02 06:05 UTC, ptrvsrg commented
@nipoks тебе нужен ПР? Если нет, закрой плз

2024-11-02 14:58 UTC, closed without merging