Manda 19 reg page
mandarine-io/Frontend pull request #4
Opened 2024-10-27 11:08 UTC by nipoks

2024-10-28 05:11 UTC, ptrvsrg requested changes

2024-10-28 05:11 UTC, ptrvsrg commented on src/pages/Register/Register.tsx
> +                                        className={`custom ${errors.username ? 'error' : ''}`}
нормально стили называем, без `custom`, `bar`, `foo` и `hui`

2024-10-28 05:11 UTC, ptrvsrg commented on src/pages/Register/Register.tsx
> +                                    <IonText className={"ion-text-right"} color="danger"> {errors.username?.message}</IonText>
Зачем пробел перед текстом?

2024-10-28 05:11 UTC, ptrvsrg commented on src/pages/Register/Register.tsx
> +
newline naher?

2024-10-28 05:11 UTC, ptrvsrg commented on src/pages/Register/Register.tsx
> +                                        onIonInput={(e) => {
Вынеси функцию

2024-10-28 05:11 UTC, ptrvsrg commented on src/pages/Register/RegisterPage.schema.ts
> +                                .matches(/^[A-Za-z0-9!@#$%^&*(),.?":{}|<>]+$/, 'Пароль должен содержать только английские буквы и разрешенные символы')
Зачем все эти проверки, если есть zxcvbn?

2024-10-28 05:11 UTC, ptrvsrg commented on src/pages/Register/RegisterPage.schema.ts
> +        username: yup.string()
```go
func UsernameValidator(fl validator.FieldLevel) bool {
	username, ok := fl.Field().Interface().(string)
	if !ok {
		return false
	}

	matched, err := regexp.MatchString("^[a-z][a-z0-9_]{1,255}$", username)
	return err == nil && matched
}
```

2024-10-28 05:11 UTC, ptrvsrg commented on src/pages/Register/RegisterPage.schema.ts
> +                                .matches(/^(?:[a-zA-Z\d!#$%&'*+/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+(?:\.[a-zA-Z\d!#$%&'*+/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+)*|"(?:[\x01
`Почта должна быть формата: example@mail.ru` -> `Неверный формат почты`

2024-10-28 05:11 UTC, ptrvsrg commented on src/pages/Register/Register.tsx
> +                            disabled={passwordStrength < 3}>
помимо этого нужно проверять, что в `errors` нет ошибок

2024-10-28 05:11 UTC, ptrvsrg commented on src/pages/Register/Register.tsx
> +                            style={{marginTop: "20%"}}
margin кал + процент кал (если он не 100)
Сделай у контайнера gap и всо

2024-10-28 05:11 UTC, ptrvsrg commented on src/pages/Register/Register.tsx
> +                        <div className="ion-margin-top" style={{display: "flex", justifyContent: "center"}}>
-> css

2024-10-28 05:11 UTC, ptrvsrg commented on src/pages/Register/Register.tsx
> +                            <IonText color="secondary" style={{textDecoration: "underline"}} onClick={() => {router.push('/', 'root')}}>Войти</IonText>
-> css

2024-10-28 05:11 UTC, ptrvsrg commented on src/pages/Register/Register.tsx
> +                    <img src={logoWithoutText} alt="logo" width="17%" />
-> css

2024-10-28 05:11 UTC, ptrvsrg commented on src/pages/Register/RegisterPage.schema.ts
> +    repPassword: string
-> passwordConfirm

2024-10-28 05:14 UTC, ptrvsrg requested changes

2024-10-28 05:14 UTC, ptrvsrg commented on env/dev
> +VITE_BACKEND_URL=https://dev.mandarine-app.ru/api
Что-то мне вообще не нравится, что креды здесь лежат
Давай файл переименуем в `.env.example` и переменные среды пустыми сделаем

2024-10-28 05:32 UTC, ptrvsrg commented on src/pages/Register/Register.tsx
> +        resolver: yupResolver(registerFormSchema),
Добавь `mode: onBlur`
тогда ошибки появятся сразу после выхода с инпута, а не после нажатия на кнопку

2024-10-28 05:36 UTC, ptrvsrg requested changes

2024-10-28 05:36 UTC, ptrvsrg commented on src/pages/Register/RegisterPage.schema.ts
> +                                .matches(/^[A-Za-z0-9!@#$%^&*(),.?":{}|<>]+$/, 'Пароль должен содержать только английские буквы и разрешенные символы')
Лучше накинь кастомную проверку с использованием zxcvbn

2024-10-28 05:36 UTC, ptrvsrg commented on src/pages/Register/Register.tsx
> +            await authClient.register( {
Можно просто 

```ts
await authClient.register(data)
```

2024-10-28 05:36 UTC, ptrvsrg commented on src/pages/Register/Register.tsx
> +            <IonContent scrollY={false}>
почему скролл убрал? Есть уверенность что в любой экран поместится?

2024-11-01 16:12 UTC, nipoks commented on src/pages/Register/Register.tsx
> +                        <h1>Регистрация</h1>
Возражаю, я в точности сделал как в доке. Нету свойства задать размер текста внутри их тега

2024-11-01 17:22 UTC, nipoks commented on src/pages/Register/RegisterPage.schema.ts
> +                                .matches(/^(?:[a-zA-Z\d!#$%&'*+/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+(?:\.[a-zA-Z\d!#$%&'*+/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+)*|"(?:[\x01
Не пон

2024-11-01 17:38 UTC, nipoks commented on src/pages/Register/Register.tsx
> +                            style={{marginTop: "20%"}}
Нууу тут скорее не соглашусь, кнопка находится вместе с инпутами и надписью под ней. gap выставит для всех одинаковые отступы шо мягко говоря не то чтобы нужно

2024-11-01 17:48 UTC, nipoks commented on env/dev
> +VITE_BACKEND_URL=https://dev.mandarine-app.ru/api
Не пон, сделал в точности как в тиграх

2024-11-01 18:18 UTC, nipoks commented on src/pages/Register/Register.tsx
> +                    <img src={logoWithoutText} alt="logo" width="17%" />
Резонно ли лишь 1 свойство выносить в функцию css в 4 строчки?

2024-11-02 04:17 UTC, ptrvsrg commented on src/pages/Register/Register.tsx
> +                            style={{marginTop: "20%"}}
в любом случае % плохо

2024-11-02 04:18 UTC, ptrvsrg commented on env/dev
> +VITE_BACKEND_URL=https://dev.mandarine-app.ru/api
еще раз, креды в репе хранить ай-яй-яй
не знаю, что еще добавить, сверху все описал

2024-11-02 04:59 UTC, nipoks commented on src/pages/Register/Register.tsx
> +                            style={{marginTop: "20%"}}
исправим на пиксели

2024-11-02 05:00 UTC, nipoks commented on env/dev
> +VITE_BACKEND_URL=https://dev.mandarine-app.ru/api
лучше микро созвон, я не вдупляю что где куда

2024-11-02 16:13 UTC, ptrvsrg requested changes

2024-11-09 18:13 UTC, nipoks commented on src/contexts/AuthContext/AuthContext.tsx
> +        register: async (input) => {
Не пон, всм убрать из клиента

2024-11-10 11:05 UTC, ptrvsrg commented on src/api/v0/auth.ts
> +import { createRequest } from "../createRequest"
`src/api/v0/auth.ts` -> `src/api/v0/auth/auth.requests.ts`

2024-11-10 11:13 UTC, ptrvsrg commented on src/common/interceptors/AuthInterceptor.tsx
> +            if (!authClient.isAuthenticated()) {
мне не нравится, что перехватываются все запросы и если есть auth state добавляется хедер

а если пользователь авторизован, но нужно отправить запрос без токена? твой подход не безопасен и нагружает больше нужно сеть

Необходимо рядом с `createRequest` положить

```
export interface RequestConfig extends AxiosRequestConfig {
    authorized?: boolean
}
```
и `createRequest` на вход будет получать `RequestConfig`

в перехватчике кастить к этому типу конфигу и проверять этот флажок + в авторизованных запросах указывать этот флаг

2024-11-10 11:14 UTC, ptrvsrg commented on src/api/createRequest.ts
> +export async function createRequest<T>(config: AxiosRequestConfig): Promise<T> {
Фиксани инпут (отписал в перехватчике)

2024-11-10 11:16 UTC, ptrvsrg commented on src/api/v0/auth.ts
> +export const logoutRequest = async () => {
запрос авторизованный, добавь флаг (отписал в перехватчике)

2024-11-10 11:19 UTC, ptrvsrg commented on src/components/ProgressBarSafetyPassword.tsx
> +    const getProgressBarColor = (score: number) => {
Давай в массив текст положим и будем по индексу получать

![image](https://github.com/user-attachments/assets/9b269b6a-b740-4ee7-8b51-f48d563d3475)

2024-11-10 11:19 UTC, ptrvsrg commented on src/components/ProgressBarSafetyPassword.tsx
> +    const getStrengthPassword = (score: number) => {
Смотри выше про массив

2024-11-10 11:19 UTC, ptrvsrg commented on src/components/ProgressBarSafetyPassword.tsx
> +                ></IonProgressBar>
`></IonProgressBar>` -> `/>`

2024-11-10 11:20 UTC, ptrvsrg commented on src/contexts/AuthContext/AuthContext.tsx
> +            if (state !== undefined && state.accessToken !== undefined) {
`if (state?.accessToken) {`

2024-11-10 11:21 UTC, ptrvsrg commented on src/contexts/AuthContext/AuthContext.tsx
> +        register: async (input) => {
че не убрал то?

2024-11-10 11:22 UTC, ptrvsrg commented on src/contexts/AuthContext/AuthContext.types.ts
> +    name: string
username?

2024-11-10 11:22 UTC, ptrvsrg commented on src/contexts/AuthContext/AuthContext.types.ts
> +    register: (input: RegisterInput) => void
убрать

2024-11-10 11:24 UTC, ptrvsrg commented on src/pages/Register/Register.tsx
> +                    ></IonAlert>
`></IonAlert>` -> `/>`

2024-11-10 11:25 UTC, ptrvsrg commented on src/pages/Register/Register.tsx
> +                            disabled={
```
disabled={passwordStrength < 3 || errors.password || errors.passwordConfirm || errors.email || errors.username}
```

2024-11-10 11:25 UTC, ptrvsrg commented on src/pages/Register/Register.tsx
> +                            disabled={
или проверь `disabled={passwordStrength < 3 || errors}`

2024-11-10 11:27 UTC, ptrvsrg commented on src/routes/routes.tsx
> +import React from 'react'
бля, почисти сразу лишнее, все эти комменты

2024-11-10 11:27 UTC, ptrvsrg commented on src/routes/Tabs.tsx
> +const Tabs: React.FC = () => {
бля почисти сразу все, потом забудется
удали все лишние роуты

2024-11-11 04:09 UTC, nipoks commented on src/contexts/AuthContext/AuthContext.tsx
> +        register: async (input) => {
![image](https://github.com/user-attachments/assets/56905079-8c57-4ec6-a23c-5cf0ae74f5d6)

2024-11-14 11:44 UTC, nipoks commented on src/pages/Register/Register.tsx
> +                            disabled={
Поправил, но чисто проверка на errors не работает. Всегда true

2024-11-14 11:46 UTC, nipoks commented on src/routes/routes.tsx
> +import React from 'react'
все импорты нужны. А комменты я оставил чтобы ребятам наглядный пример как подключать новые маршруты

2024-11-14 11:47 UTC, nipoks commented on src/routes/Tabs.tsx
> +const Tabs: React.FC = () => {
аналогично, если ты про                     <Redirect to="/tabs/search"/>
Не хочу убирать чтобы потом, когда появятся табы не вспоминать как добавлять главную страницу при входе

2024-11-14 12:17 UTC, nipoks commented on src/api/v0/auth.ts
> +export const loginRequest = async (input: LoginInput) => {
Ниже конечно указан тип output но оке: export async function loginRequest(input: LoginInput): Promise<LoginOutput> {
Тогда аналогично и ниже refresh нужно указать

2024-11-14 12:21 UTC, ptrvsrg commented on src/contexts/AuthContext/AuthContext.tsx
> +        register: async (input) => {
Да блять, просто выпили из AuthClient и добавь в папку api/v0/auth

Похуй на 2факторку

2024-11-14 14:20 UTC, ptrvsrg requested changes

2024-11-14 14:20 UTC, ptrvsrg commented on src/components/ProgressBarSafetyPassword.tsx
> +    const getProgressBarColor = (score: number) => {
Лучше мапа

2024-11-21 05:17 UTC, ptrvsrg requested changes

2024-11-21 05:17 UTC, ptrvsrg commented on src/api/createRequest.ts
> +        console.log(data)
Debug

2024-11-21 05:17 UTC, ptrvsrg commented on src/api/v0/auth/auth.requests.ts
> +    console.log(input)
debug

2024-11-21 05:17 UTC, ptrvsrg commented on src/common/interceptors/AuthInterceptor.tsx
> +            if (accessToken && configRequest.authorized) {
Почему это здесь?

2024-11-21 05:17 UTC, ptrvsrg commented on src/common/interceptors/AuthInterceptor.tsx
> +            if (accessToken && configRequest.authorized) {
перехватчик по прежнему работает неверно, зачем все изменил то по сравнению с тигриным?

2024-11-21 13:08 UTC, ptrvsrg commented on src/common/interceptors/AuthInterceptor.tsx
> +                if (authState === undefined) return config
Почему?

2024-11-21 14:09 UTC, ptrvsrg commented on src/common/interceptors/AuthInterceptor.tsx
> +                    router.push('/', 'root');
/login

2024-11-21 14:10 UTC, ptrvsrg commented on src/common/interceptors/AuthInterceptor.tsx
> +                if (authState === undefined) return config
УДАЛИ

2024-11-22 11:46 UTC, merged