добавил восстановление пароля
mandarine-io/Frontend pull request #5
Opened 2024-11-01 18:25 UTC by SP4YD

Работы с бэком пока нет, нужен конфиг файл
И проверки пароля через zxcvbn, нужно сначала подтянуть <ProgressBarSafetyPassword>

2024-11-02 05:08 UTC, nipoks commented on src/api/createRequest.ts
> +interface ErrorResponse {
Мне сережа писал про ошибку от бэка, у себя поправил. При решении конфликта выберем верный файл

2024-11-02 05:11 UTC, nipoks commented on src/contexts/RecoveyContext/RecoveryContext.tsx
> +const useRecoveryContext = (): { recoveryClient: RecoveryClient } => {
Думаю не стоит выделять отдельного провайдера для восстановления. В AuthContext же можно просто прикрутить эти 3 метода и усе

2024-11-02 05:12 UTC, nipoks commented on src/pages/PasswordRecovery/PasswordRecoveryCodePage.schema.ts
> +            .max(6, 'Длина кода 6 символов')
неужели нельзя задать маску по которой будет проверка на ровно 6 символов? Попахивает

2024-11-02 05:14 UTC, nipoks commented on src/pages/PasswordRecovery/PasswordRecoveryNewPasswordPage.schema.ts
> +            .matches(/[!@#$%^&*(),.?":{}|<>]/, 'Пароль должен содержать хотя бы один специальный символ'),
Посмотрим что сережа в моем пр скажет на проверку пароля, ну и собсна изменить на zxcvb

2024-11-02 05:17 UTC, nipoks commented on src/pages/PasswordRecovery/PasswordRecoveryNewPasswordPage.schema.ts
> +        repPassword: yup.string().required('Поле обязательно для заполнения')
поправили на  passwordConfirm

2024-11-02 06:03 UTC, ptrvsrg commented on src/contexts/RecoveyContext/RecoveryContext.tsx
> +const useRecoveryContext = (): { recoveryClient: RecoveryClient } => {
@nipoks помоги по-братски ему зачать в папке api методы

2024-11-02 06:04 UTC, ptrvsrg requested changes

2024-11-02 06:04 UTC, ptrvsrg commented on src/pages/PasswordRecovery/PasswordRecoveryCodePage.schema.ts
> +            .max(6, 'Длина кода 6 символов')
вроде как length есть

2024-11-02 06:04 UTC, ptrvsrg commented on src/pages/PasswordRecovery/PasswordRecoveryEmailPage.schema.ts
> +                                .matches(/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,'Почта должна быть формата: example@mail.ru'),
чекни у Никиты в ПР валидацию email

2024-11-02 13:09 UTC, nipoks commented on src/pages/PasswordRecovery/PasswordRecovery.tsx
> +                        <div className="logo-container">
Сереж, на стилизованных компонентах будем двигаться? Мне чисто глазам приятнее ими пользоваться чем базовые тэги с классами

2024-11-02 13:13 UTC, nipoks commented on src/pages/PasswordRecovery/PasswordRecovery.tsx
> +            }, 2000);
Я использовал компонент <IonAlert> и там можно в пустую опласть нажать либо на кнопку закрыть. Не знае как себя ведет данный, но подозрение что закрывается спустя таймер. Не совсем интуитивная история, не? да и функции обработчики кнопок жирные получаются

2024-11-02 13:20 UTC, nipoks commented
А нет такого ощущения, что получился фарш? у нас в одном жирнющем файле 3 разные страницы.... 1) Либо добавить в AuthContext поле, где будем записывать стадию восстановления пароля (1 2 3 например) и сделать 3 страницы отдельные. либо схлопнуть в один компонент и просто отображать нужные ()

2024-11-02 13:23 UTC, nipoks commented on src/contexts/RecoveyContext/RecoveryContext.tsx
> +const useRecoveryContext = (): { recoveryClient: RecoveryClient } => {
Не совсем понял, файл createRequest я переделал. А методы предлагаю в AuthContext добавить

2024-11-02 13:25 UTC, nipoks commented on src/pages/PasswordRecovery/PasswordRecoveryEmailPage.schema.ts
> +                                .matches(/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,'Почта должна быть формата: example@mail.ru'),
И надпись на "Неверный формат почты" изменить

2024-11-02 13:26 UTC, nipoks commented on src/assets/logoWText.svg
Ну и я прислушался к тебе и назвал logoWithoutText )

2024-11-02 14:45 UTC, ptrvsrg commented on src/contexts/RecoveyContext/RecoveryContext.tsx
> +const useRecoveryContext = (): { recoveryClient: RecoveryClient } => {
схуяли

2024-11-02 14:47 UTC, ptrvsrg commented on src/pages/PasswordRecovery/PasswordRecoveryNewPasswordPage.schema.ts
> +            .matches(/[!@#$%^&*(),.?":{}|<>]/, 'Пароль должен содержать хотя бы один специальный символ'),
чекай как у Никитос в ПР

2024-11-02 14:48 UTC, ptrvsrg commented on src/pages/PasswordRecovery/PasswordRecovery.tsx
> +                        <div className="logo-container">
я за стили css)

2024-11-02 16:12 UTC, ptrvsrg requested changes

2024-11-08 12:50 UTC, SP4YD commented
Исправил все замечания

2024-11-14 14:58 UTC, ptrvsrg commented on src/pages/PasswordRecovery/PasswordRecovery.context.ts
> +    recoveryState?: RecoveryState;
state

2024-11-14 14:58 UTC, ptrvsrg commented on src/pages/PasswordRecovery/PasswordRecovery.context.ts
> +    updateState: { setState: (input: any) => void };
updateState: (input: RecoveryState) => void;

2024-11-14 14:58 UTC, ptrvsrg commented on src/pages/PasswordRecovery/modules/Email/Email.tsx
> +            updateState.setState(data);
updateState(data);

2024-11-15 09:02 UTC, SP4YD commented
Вроде всё поправил. осталось только добавить ProgressBarSafetyPassword, но я лучше подожду пока Никита его исправит и зальёт, чтоб конфликтов не было

2024-11-28 15:24 UTC, SP4YD commented
Вот теперь вроде збс

2024-12-19 15:58 UTC, merged