MANDA-46: [FE] Сделать экран подтверждения регистрации (верстка + логика)
mandarine-io/Frontend pull request #7
Opened 2024-11-28 14:28 UTC by vitalioo

1. Доделать выравнивание по центру для  "Введите 6-значный ... "
2. Поискать в Ionic компоненты для ввода кода

2024-11-28 14:40 UTC, nipoks commented on src/pages/ConfirmRegister/ConfirmRegister.tsx
> +            }
вместо throw просто установи сообщение и покажи модалку  ```setAlertMessage(response.message)
            setIsOpenAlert(true)```

2024-11-28 14:41 UTC, nipoks commented on src/pages/ConfirmRegister/ConfirmRegister.tsx
> +            }
и route на страницу регистрации

2024-11-28 14:54 UTC, ptrvsrg requested changes

2024-11-28 14:54 UTC, ptrvsrg commented on src/api/v0/auth/auth.requests.ts
> +const BACKEND_URL = `https://dev.mandarine-app.ru/api/v0/auth`
В попку за такое

2024-11-28 14:54 UTC, ptrvsrg commented on src/api/v0/auth/auth.requests.ts
> +    return await createRequest<ErrorResponse>({
возвращай void

2024-11-28 14:54 UTC, ptrvsrg commented on src/contexts/RegisterContext/RegisterContext.types.ts
> +    email: string;
email?: string;

2024-11-28 14:54 UTC, ptrvsrg commented on src/contexts/RegisterContext/RegisterContext.tsx
> +        email: '',
email: undefined,

2024-11-28 14:54 UTC, ptrvsrg commented on src/pages/ConfirmRegister/ConfirmRegister.tsx
> +                                        type='text'
type="number"

2024-11-28 14:54 UTC, ptrvsrg commented on src/pages/Register/Register.tsx
> +    const [, setRegistrationState] = useRegistrationContext();
измени возвращаемое значение на объект

2024-11-28 14:54 UTC, ptrvsrg commented on src/pages/ConfirmRegister/ConfirmRegisterProvider.tsx
> +const ConfirmRegisterProvider: React.FC = () => {
RegisterGroup

2024-12-12 15:38 UTC, vitalioo commented
![image](https://github.com/user-attachments/assets/64e28871-aebf-480f-b625-d3b577757c97)
![image](https://github.com/user-attachments/assets/53b06939-d0f9-43a7-bc98-db2f54f0aef5)
![image](https://github.com/user-attachments/assets/89856053-ca91-4478-bcb0-3237f516758a)

Могу попробовать сделать квадратики для ввода через шесть отдельных IonInput

2024-12-20 05:53 UTC, vitalioo commented
![image](https://github.com/user-attachments/assets/bd229219-0b69-4ff3-aa8d-fcb864bcea8d)
![image](https://github.com/user-attachments/assets/9f9e1fc7-9216-4ad3-a538-d889a171ba40)
![image](https://github.com/user-attachments/assets/c0ab594d-f0ad-4f9e-b92f-94062cc0ef7a)

2024-12-20 07:40 UTC, merged